server:
  port: 8081
  servlet:
    context-path: /auth

# Logging configurations
logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            security: DEBUG