server:
  port: 8080
  servlet:
    context-path: /

security:
#  basic:
#    enabled: false
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/user/me

spring:
  thymeleaf:
    cache: false