server:
  port: 8080
  servlet:
    context-path: /
  session:
    cookie:
      name: UI2SESSION

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/user/me

spring:
  thymeleaf:
    cache: false

  # Debug spring security
  security:
    user:
      name: chenbin
      password: chenbin

# Logging configurations
logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            security: DEBUG